/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.falkolab.callog;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;

import android.database.Cursor;
import android.net.Uri;
import android.provider.CallLog;

@Kroll.module(name = "FalkolabCallog", id = "com.falkolab.callog")
public class FalkolabCallogModule extends KrollModule {
	@Kroll.constant
	public static final int INCOMING_TYPE = CallLog.Calls.INCOMING_TYPE;
	@Kroll.constant
	public static final int OUTGOING_TYPE = CallLog.Calls.OUTGOING_TYPE;
	@Kroll.constant
	public static final int MISSED_TYPE = CallLog.Calls.MISSED_TYPE;
	@Kroll.constant
	public static final int VOICEMAIL_TYPE = CallLog.Calls.VOICEMAIL_TYPE;

	@Kroll.constant
	public static final String CACHED_LOOKUP_URI = CallLog.Calls.CACHED_LOOKUP_URI;
	@Kroll.constant
	public static final String CACHED_MATCHED_NUMBER = CallLog.Calls.CACHED_MATCHED_NUMBER;
	@Kroll.constant
	public static final String CACHED_NAME = CallLog.Calls.CACHED_NAME;
	@Kroll.constant
	public static final String CACHED_NORMALIZED_NUMBER = CallLog.Calls.CACHED_NORMALIZED_NUMBER;
	@Kroll.constant
	public static final String CACHED_NUMBER_LABEL = CallLog.Calls.CACHED_NUMBER_LABEL;
	@Kroll.constant
	public static final String CACHED_NUMBER_TYPE = CallLog.Calls.CACHED_NUMBER_TYPE;
	@Kroll.constant
	public static final String CACHED_PHOTO_ID = CallLog.Calls.CACHED_PHOTO_ID;
	@Kroll.constant
	public static final String CACHED_PHOTO_URI = CallLog.Calls.CACHED_PHOTO_URI;
	@Kroll.constant
	public static final String CONTENT_ITEM_TYPE = CallLog.Calls.CONTENT_ITEM_TYPE;
	@Kroll.constant
	public static final String CONTENT_TYPE = CallLog.Calls.CONTENT_TYPE;
	@Kroll.constant
	public static final String COUNTRY_ISO = CallLog.Calls.COUNTRY_ISO;
	@Kroll.constant
	public static final String DATA_USAGE = CallLog.Calls.DATA_USAGE;
	@Kroll.constant
	public static final String DATE = CallLog.Calls.DATE;
	@Kroll.constant
	public static final String DEFAULT_SORT_ORDER = CallLog.Calls.DEFAULT_SORT_ORDER;
	@Kroll.constant
	public static final String DURATION = CallLog.Calls.DURATION;
	@Kroll.constant
	public static final String EXTRA_CALL_TYPE_FILTER = CallLog.Calls.EXTRA_CALL_TYPE_FILTER;
	@Kroll.constant
	public static final String FEATURES = CallLog.Calls.FEATURES;
	@Kroll.constant
	public static final int FEATURES_VIDEO = CallLog.Calls.FEATURES_VIDEO;
	@Kroll.constant
	public static final String GEOCODED_LOCATION = CallLog.Calls.GEOCODED_LOCATION;

	@Kroll.constant
	public static final String IS_READ = CallLog.Calls.IS_READ;
	@Kroll.constant
	public static final String LIMIT_PARAM_KEY = CallLog.Calls.LIMIT_PARAM_KEY;
	@Kroll.constant
	public static final String NEW = CallLog.Calls.NEW;
	@Kroll.constant
	public static final String NUMBER = CallLog.Calls.NUMBER;
	@Kroll.constant
	public static final String NUMBER_PRESENTATION = CallLog.Calls.NUMBER_PRESENTATION;
	@Kroll.constant
	public static final String OFFSET_PARAM_KEY = CallLog.Calls.OFFSET_PARAM_KEY;

	@Kroll.constant
	public static final String PHONE_ACCOUNT_COMPONENT_NAME = CallLog.Calls.PHONE_ACCOUNT_COMPONENT_NAME;
	@Kroll.constant
	public static final String PHONE_ACCOUNT_ID = CallLog.Calls.PHONE_ACCOUNT_ID;
	@Kroll.constant
	public static final int PRESENTATION_ALLOWED = CallLog.Calls.PRESENTATION_ALLOWED;
	@Kroll.constant
	public static final int PRESENTATION_PAYPHONE = CallLog.Calls.PRESENTATION_PAYPHONE;
	@Kroll.constant
	public static final int PRESENTATION_RESTRICTED = CallLog.Calls.PRESENTATION_RESTRICTED;
	@Kroll.constant
	public static final int PRESENTATION_UNKNOWN = CallLog.Calls.PRESENTATION_UNKNOWN;
	@Kroll.constant
	public static final String TRANSCRIPTION = CallLog.Calls.TRANSCRIPTION;
	@Kroll.constant
	public static final String TYPE = CallLog.Calls.TYPE;
	@Kroll.constant
	public static final String VOICEMAIL_URI = CallLog.Calls.VOICEMAIL_URI;

	// Standard Debugging variables
	private static final String LCAT = "FalkolabCallogModule";
	private static final boolean DBG = TiConfig.LOGD;

	@Kroll.method
	public Object[] query(String[] projection, String selection,
			String[] selectionArgs, String sortOrder) {		
		Uri allCalls = Uri.parse("content://call_log/calls");
		TiApplication tiApp = TiApplication.getInstance();
		Cursor cursor = tiApp.getContentResolver().query(allCalls, projection,
				selection, selectionArgs, sortOrder);

		ArrayList<Map<String, String>> data = new ArrayList<Map<String, String>>();
		String[] columnNames = cursor.getColumnNames();

		if (cursor.moveToFirst()) {
			do {
				Map<String, String> value = new HashMap<String, String>();
				for (int i = 0; i < columnNames.length; i++) {
					value.put(columnNames[i], cursor.getString(i));
				}
				data.add(value);

			} while (cursor.moveToNext());
		}
		cursor.close();

		return data.toArray(new Object[data.size()]);
	}
	
	/**
	 * Query the call log database for the last dialed number. 
	 * @return
	 */
	@Kroll.method
	public String getLastOutgoingCall() {
		return CallLog.Calls.getLastOutgoingCall(TiApplication.getInstance());
	}
}
